language: rust

rust: nightly-2016-10-21

addons:
  apt:
    packages:
    - ruby

install:
  - git clone https://github.com/aquynh/capstone
  - (cd capstone && git checkout 3.0.4 && sudo make install)

script:
  - ./test
  - ./test-release
