[package]
name = "dora"
version = "0.0.1"
authors = ["Dominik Inf√ºhr <dominik.infuehr@gmail.com>"]

[dependencies]
rustc-serialize = "0.3"
docopt = "0.7"
byteorder = "*"
libc = "*"
time = "*"
winapi = "*"
kernel32-sys = "*"
dora-parser = { path = "lib/dora-parser" }


[dependencies.capstone]
git = "https://github.com/ebfe/rust-capstone.git"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
