[package]
name = "dora"
version = "0.0.1"
authors = ["Dominik Inf√ºhr <dominik.infuehr@gmail.com>"]

[dependencies]
rustc-serialize = "*"
docopt = "*"
byteorder = "*"
libc = "*"
time = "*"

[dependencies.capstone]
git = "https://github.com/ebfe/rust-capstone.git"

# need for -fno-omit-frame-pointer
[profile.release]
debug = true
