[package]
name = "dora-asm"
version = "0.0.1"
authors = ["Dominik Inf√ºhr <dominik.infuehr@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.*"
