[package]
name = "dora"
version = "0.0.2"
authors = ["Dominik Inf√ºhr <dominik.infuehr@gmail.com>"]
description = "The Dora programming language"
homepage = "https://github.com/dinfuehr/dora"
repository = "https://github.com/dinfuehr/dora"
build = "build.rs"
license = "MIT"
edition = "2018"

[features]
default = ["capstone"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
docopt = "1.1.*"
byteorder = "*"
lazy_static = "*"
libc = "0.2.*"
time = "0.1.*"
capstone = { version = "0.6.*", optional = true }
dora-asm = { path = "../dora-asm", version = "0.0.1" }
dora-parser = { path = "../dora-parser", version = "0.0.2" }
threadpool = "*"
crossbeam-deque = "*"
rand = "*"
regex = "1.3.*"
scoped_threadpool = "*"
parking_lot = "*"
fixedbitset = "*"
num_cpus = "*"
num-traits = "0.2"
num-derive = "0.3"
memoffset = "*"

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["memoryapi"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "7.0.*"

[lib]
name = "dora"
path = "src/lib.rs"

[[bin]]
name = "dora"
path = "src/main.rs"
