[package]
name = "dora"
version = "0.0.2"
authors = ["Dominik Inf√ºhr <dominik.infuehr@gmail.com>"]
description = "The Dora programming language"
homepage = "https://github.com/dinfuehr/dora"
repository = "https://github.com/dinfuehr/dora"
build = "build.rs"
license = "MIT"
edition = "2018"

[dependencies]
rustc-serialize = "0.3.*"
docopt = "0.7.*"
byteorder = "1.3.*"
libc = "0.2.*"
time = "0.1.*"
capstone = "0.6.*"
dora-parser = { path = "../dora-parser", version = "0.0.2" }
threadpool = "1.7.*"
crossbeam-deque = "0.7.*"
rand = "0.7.*"
regex = "1.3.*"
scoped_threadpool = "0.1.*"
parking_lot = "0.9.*"
fixedbitset = "0.2.*"
num_cpus = "1.10.*"
num-traits = "0.2"
num-derive = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["memoryapi"] }

[lib]
name = "dora"
path = "src/lib.rs"

[[bin]]
name = "dora"
path = "src/main.rs"
